include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"


variables:
    NF_BEFORE_SCRIPT: |
        wget -O test_data/sample.fastq.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3-eu-west-1.amazonaws.com/metagenomic_tutorial/sample.fastq.gz;
        tar xvzf test_data/db_store/zymo.tar.gz -C test_data/db_store/
    NF_WORKFLOW_OPTS: "--reads test_data/sample.fastq.gz --db_path test_data/db_store/zymo --db_prefix zymo"


# centrifuge to dockerhub, we don't expect to change this often so a simple manual build
release-centrifuge:
    stage: custom-builds
    when: manual
    script:
        - echo ${DOCKERHUB_TOKEN} | docker login --username epi2melabs --password-stdin
        - LATEST="${DOCKERHUB_NAMESPACE}/centrifuge:latest"
        - docker build --no-cache -t "${LATEST}" -f Dockerfile_centrifuge .
        - docker push ${LATEST}


