include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"
      ref: "aws-batch"


variables:
    NF_BEFORE_SCRIPT: |
        tar xvzf test_data/db_store/zymo.tar.gz -C test_data/db_store/
    NF_WORKFLOW_OPTS: "--fastq test_data/sample.fastq.gz --db_path test_data/db_store/zymo --db_prefix zymo"


release-centrifuge:
    extends: .aux-container
    variables:
        AUX_IMAGE_NAME: "centrifuge"
        AUX_IMAGE_ENVFILE: "environment_centrifuge.yaml"
        AUX_IMAGE_DOCKERFILE: "Dockerfile_centrifuge"
