name: epi2melabs-nf-metagenomics
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - pysam
    - samtools
    - pandas
    - ncbitaxonomy
    - minimap2
    - aplanat
    - fastcat
